//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cenovnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cenovnik()
        {
            this.Rezervacijas = new HashSet<Rezervacija>();
        }
    
        public int Id { get; set; }
        public System.DateTime DatumPocetka { get; set; }
        public System.DateTime DatumKraja { get; set; }
        public int CenaPoDanu { get; set; }
        public int VoziloId { get; set; }
        public int UkupnaCena { get; set; }
    
        public virtual Vozilo Vozilo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
    }
}
