//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int Id { get; set; }
        public System.DateTime Datum_rezervacije { get; set; }
        public System.DateTime Datum_preuzimanja { get; set; }
        public System.DateTime Datum_vracanja { get; set; }
        public int VoziloId { get; set; }
        public string KlijentJmbg { get; set; }
        public int OsiguranjeId { get; set; }
        public string AgentJmbg { get; set; }
        public int CenovnikId { get; set; }
        public bool Rezervisano { get; set; }
        public int CenaRezervacije { get; set; }
    
        public virtual Vozilo Vozilo { get; set; }
        public virtual Klijent Klijent { get; set; }
        public virtual Osiguranje Osiguranje { get; set; }
        public virtual Agent Agent { get; set; }
        public virtual Cenovnik Cenovnik { get; set; }
    }
}
