//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servis
    {
        public int Id { get; set; }
        public int Cena { get; set; }
        public string Komentar { get; set; }
        public System.DateTime Datum { get; set; }
        public int VoziloId { get; set; }
        public string ServiserJmbg { get; set; }
    
        public virtual Vozilo Vozilo { get; set; }
        public virtual Serviser Serviser { get; set; }
    }
}
