//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Broj_ugovora { get; set; }
        public string Jmbg { get; set; }
        public int FilijalaId { get; set; }
    
        public virtual Filijala Filijala { get; set; }
    }
}
